apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
  - name: database
    port: 27017
    targetPort: 27017
  
  type: LoadBalancer
  selector:
    app: database