
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:

  name: mongo

spec:

  members: 3

  version: "4.2.2-ent"

  opsManager:
    configMapRef:

      name: mongo

            # Must match metadata.name in ConfigMap file

  credentials: mongo

  type: ReplicaSet
  persistent: true
